language: python
python:
  - "2.7"
# command to install dependencies
install:
  - cd ..
  - wget http://www.renpy.org/dl/6.99.12/renpy-6.99.12-sdk.tar.bz2
  - tar xf renpy-6.99.3-sdk.tar.bz2
  - rm renpy-6.99.3-sdk.tar.bz2
  - cd renpy-6.99.3-sdk
# command to run tests
script: ./renpy.sh "../ProjectGaymore/" lint
