language: python
python:
  - "2.7"
# command to install dependencies
install:
  - cd ..
  - wget http://www.renpy.org/dl/6.99.12.2/renpy-6.99.12.2-sdk.tar.bz2
  - tar xf renpy-6.99.12.2-sdk.tar.bz2
  - rm renpy-6.99.12.2-sdk.tar.bz2
  - mv renpy-6.99.12.2-sdk renpy
  - cd renpy
# command to run tests
script: ./renpy.sh "../ProjectGaymore/" lint && ./renpy.sh launcher distribute "../ProjectGaymore/"
